# Generated by Django 3.2.12 on 2022-02-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='status',
        ),
    ]
