# Generated by Django 3.2.12 on 2022-02-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
