# Generated by Django 3.2.12 on 2022-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_message_sended_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailing',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
