# Generated by Django 3.2.12 on 2022-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20220221_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='finished_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
